version: '3.8'

services:
  kafka:
    container_name: kafka
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.4.24:9092

  mongodb:
    container_name: filterdb-dev
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak-tmo
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    #      KEYCLOAK_IMPORT: realm-export.json
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/jboss/keycloak/imports

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
    networks:
      - monitor-net

volumes:
  kafka_data:
  mongodb_data:
  grafana-data:
    driver: local
  grafana-config:
    driver: local

networks:
  monitor-net:
    driver: bridge